# Form implementation generated from reading ui file 'Student_ManagementGUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(655, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(2, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 255, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 170, 125))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 255, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 255, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 170, 125))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 255, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(217, 255, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 170, 125))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 255, 205, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(179, 255, 188))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(89, 127, 94, 127))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon.fromTheme("x-office-document")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #ccc;\n"
"    color: black;\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font: 300 9pt \"URW Bookman [urw]\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(190, 255, 220);\n"
"}\n"
"QWidget {\n"
"    border-radius: 18px;\n"
"}\n"
"QFrame{\n"
"    border-radius: 18px;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 5px;\n"
"    background: white;\n"
"    padding: 4px;\n"
"}\n"
"QLabel {\n"
"    font: 600 20pt \"URW Bookman [UKWN]\";\n"
"}\n"
"QTableView {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QListView{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QMainWindow#MainWindow{\n"
"background-color: rgba(244, 255, 205, 150);\n"
"background-image: url(assets/images-removebg-preview.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: rgba(244, 255, 205, 150);\n"
"background-image: url(assets/images-removebg-preview.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setStyleSheet("background: transparent;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setObjectName("pageLogin")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pageLogin)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(parent=self.pageLogin)
        self.label_2.setStyleSheet("font: 700 18pt \"P052 [urw]\";\n"
"background-color: rgb(244, 255, 205);\n"
"border: 2px solid #bbb;\n"
"border-radius: 8px;")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setLineWidth(11)
        self.label_2.setMidLineWidth(11)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(parent=self.pageLogin)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 180))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid #bbb;\n"
"border-radius: 8px;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.usernameLabel = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("font: 300 12pt \"URW Bookman [urw]\";\n"
"border: 0px solid #bbb;\n"
"border-radius: 8px;")
        self.usernameLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout.addWidget(self.usernameLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.usernameInput = QtWidgets.QLineEdit(parent=self.widget)
        self.usernameInput.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.passwordLabel = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [urw]")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setStyleSheet("font: 300 12pt \"URW Bookman [urw]\";\n"
"border: 0px solid #bbb;\n"
"border-radius: 8px;")
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout.addWidget(self.passwordLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.passwordInput = QtWidgets.QLineEdit(parent=self.widget)
        self.passwordInput.setAutoFillBackground(False)
        self.passwordInput.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.loginButton = QtWidgets.QPushButton(parent=self.widget)
        self.loginButton.setStyleSheet("    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #ccc;\n"
"    color: black;\n"
"    border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"    font: 300 9pt \"URW Bookman [urw]\";")
        self.loginButton.setDefault(True)
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.horizontalLayout_2.addWidget(self.widget, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_12.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.pageLogin)
        self.pageMain = QtWidgets.QWidget()
        self.pageMain.setObjectName("pageMain")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pageMain)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.navSpacer = QtWidgets.QWidget(parent=self.pageMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.navSpacer.sizePolicy().hasHeightForWidth())
        self.navSpacer.setSizePolicy(sizePolicy)
        self.navSpacer.setMinimumSize(QtCore.QSize(140, 0))
        self.navSpacer.setMaximumSize(QtCore.QSize(140, 16777215))
        self.navSpacer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"bordr: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.navSpacer.setObjectName("navSpacer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.navSpacer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.navpanelLabel = QtWidgets.QLabel(parent=self.navSpacer)
        self.navpanelLabel.setStyleSheet("letter-spacing: 0.5px;\n"
"font-weight: bold;\n"
"font-size:24px;")
        self.navpanelLabel.setObjectName("navpanelLabel")
        self.verticalLayout_2.addWidget(self.navpanelLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.line = QtWidgets.QFrame(parent=self.navSpacer)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.dashboardButton = QtWidgets.QPushButton(parent=self.navSpacer)
        self.dashboardButton.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.dashboardButton.setObjectName("dashboardButton")
        self.verticalLayout_2.addWidget(self.dashboardButton)
        self.line_2 = QtWidgets.QFrame(parent=self.navSpacer)
        self.line_2.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.studentsButton = QtWidgets.QPushButton(parent=self.navSpacer)
        self.studentsButton.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.studentsButton.setObjectName("studentsButton")
        self.verticalLayout_2.addWidget(self.studentsButton)
        self.line_3 = QtWidgets.QFrame(parent=self.navSpacer)
        self.line_3.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.coursesButton = QtWidgets.QPushButton(parent=self.navSpacer)
        self.coursesButton.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.coursesButton.setObjectName("coursesButton")
        self.verticalLayout_2.addWidget(self.coursesButton)
        self.line_4 = QtWidgets.QFrame(parent=self.navSpacer)
        self.line_4.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.moreButoon = QtWidgets.QPushButton(parent=self.navSpacer)
        self.moreButoon.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.moreButoon.setObjectName("moreButoon")
        self.verticalLayout_2.addWidget(self.moreButoon)
        self.line_5 = QtWidgets.QFrame(parent=self.navSpacer)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 267, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.logoutButton = QtWidgets.QPushButton(parent=self.navSpacer)
        self.logoutButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.logoutButton.setObjectName("logoutButton")
        self.verticalLayout_2.addWidget(self.logoutButton)
        self.horizontalLayout_3.addWidget(self.navSpacer)
        self.Main = QtWidgets.QStackedWidget(parent=self.pageMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.Main.sizePolicy().hasHeightForWidth())
        self.Main.setSizePolicy(sizePolicy)
        self.Main.setStyleSheet("background-color: rgb(245, 247, 235);")
        self.Main.setObjectName("Main")
        self.pageDashboard = QtWidgets.QWidget()
        self.pageDashboard.setStyleSheet("background-color: rgb(245, 247, 235);")
        self.pageDashboard.setObjectName("pageDashboard")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageDashboard)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.dashboardLabel = QtWidgets.QLabel(parent=self.pageDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.dashboardLabel.sizePolicy().hasHeightForWidth())
        self.dashboardLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.dashboardLabel.setFont(font)
        self.dashboardLabel.setObjectName("dashboardLabel")
        self.verticalLayout_3.addWidget(self.dashboardLabel, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(parent=self.pageDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setLineWidth(1)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cardStudents = QtWidgets.QWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.cardStudents.sizePolicy().hasHeightForWidth())
        self.cardStudents.setSizePolicy(sizePolicy)
        self.cardStudents.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.cardStudents.setObjectName("cardStudents")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.cardStudents)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.studentList = QtWidgets.QListView(parent=self.cardStudents)
        self.studentList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.studentList.setObjectName("studentList")
        self.horizontalLayout_10.addWidget(self.studentList)
        self.horizontalLayout_4.addWidget(self.cardStudents)
        self.cardCourses = QtWidgets.QWidget(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.cardCourses.sizePolicy().hasHeightForWidth())
        self.cardCourses.setSizePolicy(sizePolicy)
        self.cardCourses.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.cardCourses.setObjectName("cardCourses")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.cardCourses)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.courseList = QtWidgets.QListView(parent=self.cardCourses)
        self.courseList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.courseList.setObjectName("courseList")
        self.horizontalLayout_11.addWidget(self.courseList)
        self.horizontalLayout_4.addWidget(self.cardCourses)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.cardRecent = QtWidgets.QFrame(parent=self.pageDashboard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.cardRecent.sizePolicy().hasHeightForWidth())
        self.cardRecent.setSizePolicy(sizePolicy)
        self.cardRecent.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.cardRecent.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cardRecent.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cardRecent.setObjectName("cardRecent")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.cardRecent)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.recentList = QtWidgets.QListView(parent=self.cardRecent)
        self.recentList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.recentList.setObjectName("recentList")
        self.horizontalLayout_12.addWidget(self.recentList)
        self.verticalLayout_3.addWidget(self.cardRecent)
        self.Main.addWidget(self.pageDashboard)
        self.pageStudents = QtWidgets.QWidget()
        self.pageStudents.setStyleSheet("background-color: rgb(245, 247, 235);")
        self.pageStudents.setObjectName("pageStudents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageStudents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(parent=self.pageStudents)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.addstudentButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.addstudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.addstudentButton.setObjectName("addstudentButton")
        self.horizontalLayout_5.addWidget(self.addstudentButton)
        self.editstudentButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.editstudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.editstudentButton.setObjectName("editstudentButton")
        self.horizontalLayout_5.addWidget(self.editstudentButton)
        self.enrollstudentButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.enrollstudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.enrollstudentButton.setObjectName("enrollstudentButton")
        self.horizontalLayout_5.addWidget(self.enrollstudentButton)
        self.deletestudentButton = QtWidgets.QPushButton(parent=self.frame_3)
        self.deletestudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.deletestudentButton.setObjectName("deletestudentButton")
        self.horizontalLayout_5.addWidget(self.deletestudentButton)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(parent=self.pageStudents)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.searchstudentInput = QtWidgets.QLineEdit(parent=self.frame_4)
        self.searchstudentInput.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.searchstudentInput.setObjectName("searchstudentInput")
        self.horizontalLayout_6.addWidget(self.searchstudentInput)
        self.searchstudentButton = QtWidgets.QPushButton(parent=self.frame_4)
        self.searchstudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.searchstudentButton.setObjectName("searchstudentButton")
        self.horizontalLayout_6.addWidget(self.searchstudentButton)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(parent=self.pageStudents)
        self.frame_5.setStyleSheet("border-radius: 8px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.studentTabs = QtWidgets.QTabWidget(parent=self.frame_5)
        self.studentTabs.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.studentTabs.setObjectName("studentTabs")
        self.studentlistTable = QtWidgets.QWidget()
        self.studentlistTable.setObjectName("studentlistTable")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.studentlistTable)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.studentTable_2 = QtWidgets.QTableView(parent=self.studentlistTable)
        self.studentTable_2.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.studentTable_2.setObjectName("studentTable_2")
        self.horizontalLayout_8.addWidget(self.studentTable_2)
        self.studentTabs.addTab(self.studentlistTable, "")
        self.studentreportTable = QtWidgets.QWidget()
        self.studentreportTable.setObjectName("studentreportTable")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.studentreportTable)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.studentreportList = QtWidgets.QListView(parent=self.studentreportTable)
        self.studentreportList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"")
        self.studentreportList.setObjectName("studentreportList")
        self.verticalLayout_6.addWidget(self.studentreportList)
        self.getstudentreportButton = QtWidgets.QPushButton(parent=self.studentreportTable)
        self.getstudentreportButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.getstudentreportButton.setObjectName("getstudentreportButton")
        self.verticalLayout_6.addWidget(self.getstudentreportButton)
        self.studentTabs.addTab(self.studentreportTable, "")
        self.horizontalLayout_7.addWidget(self.studentTabs)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.Main.addWidget(self.pageStudents)
        self.pageCourses = QtWidgets.QWidget()
        self.pageCourses.setStyleSheet("background-color: rgb(245, 247, 235);")
        self.pageCourses.setObjectName("pageCourses")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageCourses)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(parent=self.pageCourses)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.addcourseButton = QtWidgets.QPushButton(parent=self.frame_6)
        self.addcourseButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.addcourseButton.setObjectName("addcourseButton")
        self.horizontalLayout_13.addWidget(self.addcourseButton)
        self.editcourseButton = QtWidgets.QPushButton(parent=self.frame_6)
        self.editcourseButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.editcourseButton.setObjectName("editcourseButton")
        self.horizontalLayout_13.addWidget(self.editcourseButton)
        self.deletecourseButton = QtWidgets.QPushButton(parent=self.frame_6)
        self.deletecourseButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.deletecourseButton.setObjectName("deletecourseButton")
        self.horizontalLayout_13.addWidget(self.deletecourseButton)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(parent=self.pageCourses)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.searchcourseInput = QtWidgets.QLineEdit(parent=self.frame_7)
        self.searchcourseInput.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.searchcourseInput.setObjectName("searchcourseInput")
        self.horizontalLayout_14.addWidget(self.searchcourseInput)
        self.searchcourseButton = QtWidgets.QPushButton(parent=self.frame_7)
        self.searchcourseButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.searchcourseButton.setObjectName("searchcourseButton")
        self.horizontalLayout_14.addWidget(self.searchcourseButton)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(parent=self.pageCourses)
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.courseTab = QtWidgets.QTabWidget(parent=self.frame_8)
        self.courseTab.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.courseTab.setObjectName("courseTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.courseTable = QtWidgets.QTableView(parent=self.tab)
        self.courseTable.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.courseTable.setObjectName("courseTable")
        self.horizontalLayout_9.addWidget(self.courseTable)
        self.courseTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.coursereportList = QtWidgets.QListView(parent=self.tab_2)
        self.coursereportList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.coursereportList.setObjectName("coursereportList")
        self.verticalLayout_7.addWidget(self.coursereportList)
        self.getcoursereportButton = QtWidgets.QPushButton(parent=self.tab_2)
        self.getcoursereportButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.getcoursereportButton.setObjectName("getcoursereportButton")
        self.verticalLayout_7.addWidget(self.getcoursereportButton)
        self.courseTab.addTab(self.tab_2, "")
        self.horizontalLayout_15.addWidget(self.courseTab)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.Main.addWidget(self.pageCourses)
        self.pageMore = QtWidgets.QWidget()
        self.pageMore.setStyleSheet("background-color: rgb(245, 247, 235);")
        self.pageMore.setObjectName("pageMore")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pageMore)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_9 = QtWidgets.QFrame(parent=self.pageMore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("URW Bookman [UKWN]")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_8 = QtWidgets.QFrame(parent=self.frame_9)
        self.line_8.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_9.addWidget(self.line_8)
        self.calcgradeButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.calcgradeButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.calcgradeButton.setObjectName("calcgradeButton")
        self.verticalLayout_9.addWidget(self.calcgradeButton)
        self.line_6 = QtWidgets.QFrame(parent=self.frame_9)
        self.line_6.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_9.addWidget(self.line_6)
        self.addgradeButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.addgradeButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.addgradeButton.setObjectName("addgradeButton")
        self.verticalLayout_9.addWidget(self.addgradeButton)
        self.line_7 = QtWidgets.QFrame(parent=self.frame_9)
        self.line_7.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_9.addWidget(self.line_7)
        self.rankButton = QtWidgets.QPushButton(parent=self.frame_9)
        self.rankButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.rankButton.setObjectName("rankButton")
        self.verticalLayout_9.addWidget(self.rankButton)
        self.line_9 = QtWidgets.QFrame(parent=self.frame_9)
        self.line_9.setStyleSheet("border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_9.addWidget(self.line_9)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(parent=self.pageMore)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.frame_11.sizePolicy().hasHeightForWidth())
        self.frame_11.setSizePolicy(sizePolicy)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_12.setStyleSheet("background-color: rgb(218, 234, 171);\n"
"border-radius: 8px;\n"
"border: 1px solid #bbb;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.failingstudentList = QtWidgets.QListWidget(parent=self.frame_12)
        self.failingstudentList.setStyleSheet("background-color: rgb(244, 255, 205);\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;")
        self.failingstudentList.setObjectName("failingstudentList")
        self.verticalLayout_11.addWidget(self.failingstudentList)
        self.failinfstudentButton = QtWidgets.QPushButton(parent=self.frame_12)
        self.failinfstudentButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 1px solid #bbb;\n"
"border-radius: 8px;\n"
"font: 300 9pt \"URW Bookman [urw]\";\n"
"")
        self.failinfstudentButton.setObjectName("failinfstudentButton")
        self.verticalLayout_11.addWidget(self.failinfstudentButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_16.addWidget(self.frame_12)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.Main.addWidget(self.pageMore)
        self.horizontalLayout_3.addWidget(self.Main)
        self.stackedWidget.addWidget(self.pageMain)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.Main.setCurrentIndex(3)
        self.studentTabs.setCurrentIndex(0)
        self.courseTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "EAC STUDENT MANAGEMENT SYSTEM"))
        self.usernameLabel.setText(_translate("MainWindow", "Username"))
        self.passwordLabel.setText(_translate("MainWindow", "Password"))
        self.loginButton.setText(_translate("MainWindow", "Submit"))
        self.navpanelLabel.setText(_translate("MainWindow", "Panel"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.studentsButton.setText(_translate("MainWindow", "Students"))
        self.coursesButton.setText(_translate("MainWindow", "Courses"))
        self.moreButoon.setText(_translate("MainWindow", "MORE"))
        self.logoutButton.setText(_translate("MainWindow", "Log out"))
        self.dashboardLabel.setText(_translate("MainWindow", "Welcome"))
        self.addstudentButton.setText(_translate("MainWindow", "Add Student"))
        self.editstudentButton.setText(_translate("MainWindow", "Edit Student"))
        self.enrollstudentButton.setText(_translate("MainWindow", "Enroll Student"))
        self.deletestudentButton.setText(_translate("MainWindow", "Delete Student"))
        self.searchstudentInput.setText(_translate("MainWindow", "eg. Gol d. Roger"))
        self.searchstudentButton.setText(_translate("MainWindow", "Search"))
        self.studentTabs.setTabText(self.studentTabs.indexOf(self.studentlistTable), _translate("MainWindow", "Tab 1"))
        self.getstudentreportButton.setText(_translate("MainWindow", "Get Student Report"))
        self.studentTabs.setTabText(self.studentTabs.indexOf(self.studentreportTable), _translate("MainWindow", "Tab 2"))
        self.addcourseButton.setText(_translate("MainWindow", "Add Course"))
        self.editcourseButton.setText(_translate("MainWindow", "Edit Course"))
        self.deletecourseButton.setText(_translate("MainWindow", "Delete Course"))
        self.searchcourseInput.setText(_translate("MainWindow", "eg. MATH101"))
        self.searchcourseButton.setText(_translate("MainWindow", "Search"))
        self.courseTab.setTabText(self.courseTab.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.getcoursereportButton.setText(_translate("MainWindow", "Get Course Report"))
        self.courseTab.setTabText(self.courseTab.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.label.setText(_translate("MainWindow", "General Tools"))
        self.calcgradeButton.setText(_translate("MainWindow", "Calculate Grade"))
        self.addgradeButton.setText(_translate("MainWindow", "Add Student Grade"))
        self.rankButton.setText(_translate("MainWindow", "Get Class Ranking"))
        self.failinfstudentButton.setText(_translate("MainWindow", "Find Failing Student"))
